version: '3.0'

services:
  main:
    container_name: test
    build:
      context: .
    volumes:
      - .:/app
      - /node_modules
    ports:
      - 5000:5000
    command: npm run start
    restart: always