name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: afros/test:firsttry
  deploy:

    runs-on: ubuntu-latest
    needs:
      - docker
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2

        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOST }}


      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.PORT}} -H ${{ secrets.KNOWN_HOST }}  >> ~/.ssh/known_hosts

      #- name: Deploy with rsync
      #  run: rsync -avz ./ ${{ secrets.USERNAME }}@${{ secrets.KNOWN_HOST }}:~/home

      - name: Restart Node Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.KNOWN_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/
            docker stop afros
            docker image rm afros/test:firsttry
            docker run --name afros --rm -p 5000:5000 afros/test:firsttry